In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import sklearn.metrics as metrics
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
books = pd.read_csv('csv/BX-Books.csv', error_bad_lines=False, sep=';')
books.drop(['Image-URL-S', 'Image-URL-M', 'Image-URL-L'], axis=1, inplace=True)

users = pd.read_csv('csv/BX-Users.csv', error_bad_lines=False, sep=';')

ratings = pd.read_csv('csv/BX-Book-Ratings.csv', error_bad_lines=False, sep=';')


b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'


In [3]:
books['Year-Of-Publication'].unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980'

In [4]:
books.loc[books.ISBN == '0789466953','Year-Of-Publication'] = 2000
books.loc[books.ISBN == '0789466953','Book-Author'] = "James Buckley"
books.loc[books.ISBN == '0789466953','Publisher'] = "DK Publishing Inc"
books.loc[books.ISBN == '0789466953','Book-Title'] = "DK Readers: Creating the X-Men, How Comic Books Come to Life (Level 4: Proficient Readers)"
books.loc[books.ISBN == '078946697X','Year-Of-Publication'] = 2000
books.loc[books.ISBN == '078946697X','Book-Author'] = "Michael Teitelbaum"
books.loc[books.ISBN == '078946697X','Publisher'] = "DK Publishing Inc"
books.loc[books.ISBN == '078946697X','Book-Title'] = "DK Readers: Creating the X-Men, How It All Began (Level 4: Proficient Readers)"
books.loc[books.ISBN == '2070426769','Year-Of-Publication'] = 2003
books.loc[books.ISBN == '2070426769','Book-Author'] = "Jean-Marie Gustave Le Cl�©zio"
books.loc[books.ISBN == '2070426769','Publisher'] = "Gallimard"
books.loc[books.ISBN == '2070426769','Book-Title'] = "Peuple du ciel, suivi de 'Les Bergers"

books['Year-Of-Publication']=pd.to_numeric(books['Year-Of-Publication'], errors='coerce')
books.loc[(books['Year-Of-Publication'] > 2020) | (books['Year-Of-Publication'] == 0),'Year-Of-Publication'] = np.NAN
books['Year-Of-Publication'].fillna(round(books['Year-Of-Publication'].mean()), inplace=True)
books['Year-Of-Publication'] = books['Year-Of-Publication'].astype(np.int32)

In [5]:
ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
users.loc[(users['Age'] > 100) | (users['Age'] < 5), 'Age'] = np.nan
users['Age'] = users['Age'].fillna(users['Age'].mean())
users['Age'] = users['Age'].astype(np.int32)


In [7]:
ratings_new = ratings[ratings['ISBN'].isin(books['ISBN'])]

In [8]:
n_users = users.shape[0]
n_books = books.shape[0]
1.0-len(ratings_new)/float(n_users*n_books)

0.9999863734155897

In [9]:
ratings_implicit = ratings_new[ratings_new['Book-Rating'] == 0]
ratings_explicit = ratings_new[ratings_new['Book-Rating'] != 0]


In [10]:
counts1 = ratings_explicit['User-ID'].value_counts()
ratings_explicit = ratings_explicit[ratings_explicit['User-ID'].isin(counts1[counts1 >= 100].index)]
counts = ratings_explicit['Book-Rating'].value_counts()
ratings_explicit = ratings_explicit[ratings_explicit['Book-Rating'].isin(counts[counts >= 100].index)]

In [11]:
ratings_matrix = ratings_explicit.pivot(index='User-ID', columns='ISBN', values='Book-Rating')
userID = ratings_matrix.index
ISBN = ratings_matrix.columns
print(ratings_matrix.shape)
ratings_matrix

(449, 66574)


ISBN     0000913154  0001046438  000104687X  0001047213  0001047973  \
User-ID                                                               
2033            NaN         NaN         NaN         NaN         NaN   
2110            NaN         NaN         NaN         NaN         NaN   
2276            NaN         NaN         NaN         NaN         NaN   
4017            NaN         NaN         NaN         NaN         NaN   
4385            NaN         NaN         NaN         NaN         NaN   
...             ...         ...         ...         ...         ...   
274061          NaN         NaN         NaN         NaN         NaN   
274301          NaN         NaN         NaN         NaN         NaN   
275970          NaN         NaN         NaN         NaN         NaN   
277427          NaN         NaN         NaN         NaN         NaN   
278418          NaN         NaN         NaN         NaN         NaN   

ISBN     000104799X  0001048082  0001053736  0001053744  0001055607  ...  \
User-ID                                                              ...   
2033            NaN         NaN         NaN         NaN         NaN  ...   
2110            NaN         NaN         NaN         NaN         NaN  ...   
2276            NaN         NaN         NaN         NaN         NaN  ...   
4017            NaN         NaN         NaN         NaN         NaN  ...   
4385            NaN         NaN         NaN         NaN         NaN  ...   
...             ...         ...         ...         ...         ...  ...   
274061          NaN         NaN         NaN         NaN         NaN  ...   
274301          NaN         NaN         NaN         NaN         NaN  ...   
275970          NaN         NaN         NaN         NaN         NaN  ...   
277427          NaN         NaN         NaN         NaN         NaN  ...   
278418          NaN         NaN         NaN         NaN         NaN  ...   

ISBN     B000092Q0A  B00009EF82  B00009NDAN  B0000DYXID  B0000T6KHI  \
User-ID                                                               
2033            NaN         NaN         NaN         NaN         NaN   
2110            NaN         NaN         NaN         NaN         NaN   
2276            NaN         NaN         NaN         NaN         NaN   
4017            NaN         NaN         NaN         NaN         NaN   
4385            NaN         NaN         NaN         NaN         NaN   
...             ...         ...         ...         ...         ...   
274061          NaN         NaN         NaN         NaN         NaN   
274301          NaN         NaN        10.0         NaN         NaN   
275970          NaN         NaN         NaN         NaN         NaN   
277427          NaN         NaN         NaN         NaN         NaN   
278418          NaN         NaN         NaN         NaN         NaN   

ISBN     B0000VZEJQ  B0000X8HIE  B00013AX9E  B0001I1KOG  B000234N3A  
User-ID                                                              
2033            NaN         NaN         NaN         NaN         NaN  
2110            NaN         NaN         NaN         NaN         NaN  
2276            NaN         NaN         NaN         NaN         NaN  
4017            NaN         NaN         NaN         NaN         NaN  
4385            NaN         NaN         NaN         NaN         NaN  
...             ...         ...         ...         ...         ...  
274061          NaN         NaN         NaN         NaN         NaN  
274301          NaN         NaN         NaN         NaN         NaN  
275970          NaN         NaN         NaN         NaN         NaN  
277427          NaN         NaN         NaN         NaN         NaN  
278418          NaN         NaN         NaN         NaN         NaN  

[449 rows x 66574 columns]

In [12]:
ratings_matrix.fillna(0, inplace = True)
ratings_matrix = ratings_matrix.astype(np.int32)

In [13]:
asd = ratings_matrix.loc[2033]
for i in range(len(list(asd))):
    if asd[i] != 0:
        print(asd[i], ratings_matrix.columns[i])

7 0030020786
10 0060248025
10 0060256664
10 0060256737
10 0060950536
7 0061020419
6 0061020427
10 0061056278
8 0061056286
9 0061056294
7 0061059773
10 0133502813
8 0140386645
10 0142000663
7 0142500135
6 0192800493
10 0201632721
8 0312921098
9 0316542377
10 0316779032
10 0316779059
5 0345337662
10 0345340426
10 0375815260
10 0380775123
6 0399523308
9 0439064864
9 0439136350
9 0439139597
9 043935806X
7 0441004997
10 0451456718
10 0451456734
8 0451457781
10 0451458028
10 0451458508
10 0451458990
10 0451459423
10 0452279089
10 0471485527
6 051513628X
10 0553379534
8 0553573136
9 0590353403
2 0595006035
2 0595093019
10 0671025554
10 0671027441
10 0671519751
6 0671524313
10 0671676253
7 0688117619
8 0688149790
10 0688161162
7 0698119509
7 0716723980
7 0716724022
7 0764550039
10 0765342987
10 0765345048
8 0786861320
8 0786880007
9 0812090381
7 0812500865
10 0812516850
10 0812520157
10 0812521358
10 0812523040
10 0812523679
10 0812532554
8 0812532597
8 0812532619
8 0812532635
8 0812532961
8 0

In [18]:
def findksimilaritems(item_id, ratings, metric=metric, k=k):
    similarities=[]
    indices=[]
    ratings=ratings.T
    loc = ratings.index.get_loc(item_id)
    model_knn = NearestNeighbors(metric = metric, algorithm = 'brute')
    model_knn.fit(ratings)
    
    distances, indices = model_knn.kneighbors(ratings.iloc[loc, :].values.reshape(1, -1), n_neighbors = k+1)
    similarities = 1-distances.flatten()

    return similarities,indices

def predict_itembased(user_id, item_id, ratings, metric = metric, k=k):
    prediction= wtd_sum =0
    user_loc = ratings.index.get_loc(user_id)
    item_loc = ratings.columns.get_loc(item_id)
    similarities, indices=findksimilaritems(item_id, ratings) #similar users based on correlation coefficients
    sum_wt = np.sum(similarities)-1
    product=1
    for i in range(0, len(indices.flatten())):
        if indices.flatten()[i] == item_loc:
            continue
        else:
            product = ratings.iloc[user_loc,indices.flatten()[i]] * (similarities[i])
            wtd_sum = wtd_sum + product                              
    prediction = int(round(wtd_sum/sum_wt))
    
    #in case of very sparse datasets, using correlation metric for collaborative based approach may give negative ratings
    #which are handled here as below //code has been validated without the code snippet below, below snippet is to avoid negative
    #predictions which might arise in case of very sparse datasets when using correlation metric
    if prediction <= 0:
        prediction = 1   
    elif prediction >10:
        prediction = 10

    print ('\nPredicted rating for user {0} -> item {1}: {2}'.format(user_id,item_id,prediction))   
    
    return prediction

In [19]:
k=20
metric='correlation'
prediction = predict_itembased(2033,'0060248025',ratings_matrix)


Predicted rating for user 2033 -> item 0060248025: 4


In [21]:
from scipy.spatial.distance import pdist,squareform
squareform(pdist(ratings_matrix, metric='cosine'))

array([[0.        , 1.        , 0.95099824, ..., 1.        , 1.        ,
        1.        ],
       [1.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.95099824, 1.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 0.        , 0.99338011,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.99338011, 0.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ]])

In [31]:
cosine_similarity(ratings_matrix)
import matplotlib.pyplot as plt


array([[1.        , 0.        , 0.04900176, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.04900176, 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.00661989,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00661989, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [32]:
np.corrcoef(ratings_matrix)

array([[ 1.        , -0.00167007,  0.04681143, ..., -0.00197429,
        -0.00200219, -0.0016626 ],
       [-0.00167007,  1.        , -0.0020535 , ..., -0.00175832,
        -0.00178316, -0.00148072],
       [ 0.04681143, -0.0020535 ,  1.        , ..., -0.00242757,
        -0.00246187, -0.00204431],
       ...,
       [-0.00197429, -0.00175832, -0.00242757, ...,  1.        ,
         0.00452585, -0.00175045],
       [-0.00200219, -0.00178316, -0.00246187, ...,  0.00452585,
         1.        , -0.00177519],
       [-0.0016626 , -0.00148072, -0.00204431, ..., -0.00175045,
        -0.00177519,  1.        ]])

In [33]:
np.corrcoef(ratings_matrix.T)

MemoryError: Unable to allocate 33.0 GiB for an array with shape (66574, 66574) and data type float64

In [34]:
cosine_similarity(ratings_matrix.T)

MemoryError: Unable to allocate 33.0 GiB for an array with shape (66574, 66574) and data type float64